server:
  port: 8081

spring:
  application:
    name: api-desafio-picpay

  security:
    user:
      name: user
      password: 200622




  datasource:
    username: root
    password:
    url: jdbc:h2:mem:db_bank

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true


  flyway:
    enabled: false

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration