CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    NOME_COMPLETO VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DOCUMENT_TYPE VARCHAR(18) NOT NUll,
    DOCUMENT_VALUE varchar(18) NOT NULL UNIQUE
);
