CREATE TABLE Users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    NOME_COMPLETO VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DOCUMENT VARCHAR(18) NOT NULL UNIQUE
);

